# Use root/example as user/password credentials
version: '3.9'

services:

  ubuntu_jenkins:
    # image: we can take it form hub from your repo or we can use build command to take the code from local
    build: "jenkins/."
    restart: always
    ports: 
      - 7777:7777
    volumes:
      - jenkinsdata:/root
volumes:
  jenkinsdata:
      